export const PROJECT_TYPES_BY_GAME: Record<string, { label: string; value: string }[]> = {
  'minecraft': [
    { label: 'Моды', value: 'mods' },
    { label: 'Плагины', value: 'plugins' },
    { label: 'Сборки серверов', value: 'server-packs' },
    { label: 'Переводы', value: 'translations' },
    { label: 'Конфигурации', value: 'configs' },
    { label: 'Сборки модов', value: 'modpacks' },
    { label: 'Шейдеры', value: 'shaders' },
    { label: 'Ресурспаки', value: 'resourcepacks' },
    { label: 'Карты', value: 'maps' },
    { label: 'Схематики', value: 'schematics' },
    { label: 'Датапаки', value: 'datapacks' },
  ],
  'hytale': [
    { label: 'Моды', value: 'mods' },
    { label: 'Скрипты (C#)', value: 'scripts' },
    { label: 'Сборки серверов', value: 'server-packs' },
    { label: 'Конфигурации', value: 'configs' },
    { label: 'Переводы', value: 'translations' },
    { label: 'Модели и Ассеты', value: 'models' },
    { label: 'Миры и Карты', value: 'worlds' },
    { label: 'Инструменты', value: 'tools' },
  ],
  'voxelcore': [
    { label: 'Моды', value: 'mods' },
    { label: 'Библиотеки', value: 'libraries' },
    { label: 'Текстурпаки', value: 'texture-packs' },
    { label: 'Схематики', value: 'schematics' },
    { label: 'Миры', value: 'worlds' },
    { label: 'Сборки модов', value: 'modpacks' },
    { label: 'Ядро', value: 'core' },
    { label: 'Инструменты', value: 'tools' },
  ]
};