export const PROJECT_TAGS = {
  mod: [
    { id: 'optimization', label: 'Оптимизация' },
    { id: 'game-mechanics', label: 'Игровая механика' },
    { id: 'world-gen', label: 'Генерация мира' },
    { id: 'technology', label: 'Технологии' },
    { id: 'magic', label: 'Магия' },
    { id: 'adventure', label: 'Приключения' },
    { id: 'mobs', label: 'Мобы' },
    { id: 'equipment', label: 'Снаряжение' },
    { id: 'food', label: 'Еда' },
    { id: 'decoration', label: 'Декорации' },
    { id: 'storage', label: 'Хранение' },
    { id: 'transportation', label: 'Транспорт' },
    { id: 'library', label: 'Библиотеки (API)' },
    { id: 'utility', label: 'Утилиты' },
    { id: 'cursed', label: 'Проклятое' },
  ],
  plugin: [
    { id: 'admin', label: 'Администрирование' },
    { id: 'management', label: 'Управление' },
    { id: 'economy', label: 'Экономика' },
    { id: 'chat', label: 'Чат' },
    { id: 'protection', label: 'Защита' },
    { id: 'minigame', label: 'Мини-игры' },
    { id: 'social', label: 'Социальное' },
    { id: 'utility', label: 'Утилиты' },
    { id: 'game-mechanics', label: 'Механики' },
  ],
  shader: [
    { id: 'realistic', label: 'Реалистичные' },
    { id: 'performance', label: 'Для слабых ПК' },
    { id: 'fancy', label: 'Красивые' },
    { id: 'stylized', label: 'Стилизованные' },
    { id: 'lighting', label: 'Освещение' },
  ],
  map: [
    { id: 'schematic', label: 'Схематика' },
    { id: 'adventure', label: 'Приключения' },
    { id: 'survival', label: 'Выживание' },
    { id: 'parkour', label: 'Паркур' },
    { id: 'horror', label: 'Хоррор' },
    { id: 'minigame', label: 'Мини-игры' },
    { id: 'puzzle', label: 'Головоломка' },
    { id: 'city', label: 'Город' },
    { id: 'medieval', label: 'Средневековье' },
    { id: 'spawn', label: 'Спавн' },
    { id: 'mini-game', label: 'Мини-игры' },
    { id: 'server', label: 'Для сервера' },
  ]
};